import "@/styles/globals.css";

import { Inter } from "next/font/google";
import { twMerge } from "tailwind-merge";
import Providers from "./providers";
import { Session } from "next-auth";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
  session,
}: {
  children: React.ReactNode;
  session: Session | null;
}) {
  return (
    <html lang="en">
      <Providers session={session}>
        <body
          className={twMerge(
            "max-h-screen bg-background font-sans text-foreground antialiased",
            inter.variable,
          )}
        >
          {/* <div vaul-drawer-wrapper=""> */}
          {children}
          {/* </div> */}
        </body>
      </Providers>
    </html>
  );
}
